### ISSUE TITLE
Data Download

### ISSUE THREAD

**Issue by naveenventuri** [sunghoonim/DPSNet#1]
No such file or directory error when downloading dataset from download_traindata.sh script file

**Comment by sunghoonim** [comment]
You can download the data here 
https://lmb.informatik.uni-freiburg.de/data/demon/

**Comment by naveenventuri** [comment]
In Dataset Preparation Python code
(preparedata_train.py||preparedata_test.py) Line 59 you are trying to read
the image which you have converted to bytes i just wanted to confirm if
this imwrite(img) since its giving me an error of "unable to read the file
of specified format"
