### ISSUE TITLE
Clarification for the codes

### ISSUE THREAD

**Issue by JerryXu0907** [sunghoonim/DPSNet#13]
Hi!

Thank you for sharing the codes and your amazing paper.

I am just a beginner in this area, so I am going through your codes for some insights. However, it seems that I met some problems, mostly in architecture parts.

1. In your paper, you mention that there will be a 7x7 filter for the the first layer, but I did not manage to find such layer. I wonder if it is my misunderstanding of the code.

2. Also, you mentioned the four fixed-size average pooling blocks with size 16, 8, 4, 2. But I found the average pooling kernel size in feature_extraction class in submodule.py to be 32, 16, 8, 4. I wonder if this part is the spatial pyramid pooling you mentioned in your paper.

Thank you in advance for solving my questions!!!

**Comment by sunghoonim** [comment]
Ah.. I might mistakenly explain it on paper.
It does not include 7x7filter, and the kernel size is 32,16,8,4.

Thank you for letting me know the mistakes.

**Comment by JerryXu0907** [comment]
Thanks for your response!
