### ISSUE TITLE
Reproduce results on ETH3D

### ISSUE THREAD

**Issue by matsuren** [sunghoonim/DPSNet#15]
Hi, Thank you for sharing the code! It's great!

I'm wondering if I could reproduce the results on ETH3D in Table 2 in your paper.
I tried the following code as mentioned in README:
`python test_ETH3D.py ./dataset/ETH3D_results/ --sequence-length 3 --output-print --pretrained-dps ./pretrained/dpsnet.pth.tar `
But I got different results from the ones in the paper.

Depth Results :		
		
|abs_rel | abs_diff | sq_rel | rms | log_rms | a1 | a2 | a3	|
| --------- | --------- | --------- | --------- | ------- | --|--|--- |
|0.0952 | 0.5250 | 0.2231 | 1.0379 | 0.1743 | 0.8786 | 0.9451 | 0.9674|

Do you have any ideas what I'm missing?

**Comment by sunghoonim** [comment]
After the bug fix, is the problem still exist?
If then, it might be caused by how you set the evaluation depth range (min and max depth).

You can change the maximum depth range for the evaluation.

**Comment by matsuren** [comment]
Thanks for your reply. The problem still exists after the bug fix. 
I haven't try to change the depth range, but maybe it causes the problem.
