### ISSUE TITLE
Could not find a format to read the specified file

### ISSUE THREAD

**Issue by naveenventuri** [sunghoonim/DPSNet#2]
Line 59 in preparedata_test.py  has imageio.imread(img.tobytes()).This gives an error saying that could not find a format to read the specified file in mode 'i'

**Comment by seowok** [comment]
I am suffering from same error. Had you solve this problem?

**Comment by naveenventuri** [comment]
which os are you working on?

**Comment by sunghoonim** [comment]
I use Ubuntu 16.04

**Comment by FishHe** [comment]
I am suffering from same error.
