### ISSUE TITLE
About the efficiency

### ISSUE THREAD

**Issue by riyueshi** [sunghoonim/DPSNet#4]
Hi, 
  The depth map present in the paper is really amazing, I wonder how much time it cost to produce a single depth map?

Thanks,
Miller

**Comment by sunghoonim** [comment]
A forward pass of the proposed network takes about 0.5 seconds for 2-view matching and an additional 0.25 seconds for every new frame matched (640 × 480 image resolution).

**Comment by riyueshi** [comment]
That's great, and what about the hardware of this performance

**Comment by sunghoonim** [comment]
I test it on the computer (i7-6800K CPU, one GTX 1080Ti).

**Comment by riyueshi** [comment]
Thank you!

**Comment by zmurez** [comment]
adding
`cudnn.benchmark = True`
to test.py improved the performance from ~4s to ~.7s on a 1080Ti
